version: "3.1"
services:
  db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: okshimel
    ports:
      - "3306:3306"
    logging:
      driver: none
# docker-compose up -d
